=== cbfaucher/qtrend/src/main/resources/exchange-configuration.dtd
<!--<?xml version="1.0" encoding="UTF-8"?>-->

<!--
	<!DOCTYPE exchange-configuration SYSTEM "http://quartz.com/dtd/exchange-configuration.dtd">
-->

<!ELEMENT exchange-configuration (exchange*)>

<!ELEMENT exchange (includes?, excludes?)>
<!ATTLIST exchange name             CDATA #REQUIRED>
<!ATTLIST exchange extension        CDATA #IMPLIED>
<!ATTLIST exchange minimum-volume   CDATA #IMPLIED>
<!ATTLIST exchange minimum-price    CDATA #IMPLIED>
<!ATTLIST exchange maximum-price    CDATA #IMPLIED>

<!ELEMENT includes ((ticker+, price-volume-ratio?)|all)>
<!ELEMENT excludes (ticker+|all)>

<!ELEMENT ticker EMPTY>
<!ATTLIST ticker ticker CDATA #REQUIRED>

<!ELEMENT price-volume-ratio    EMPTY>
<!ATTLIST price-volume-ratio    average-capital-invested    CDATA #REQUIRED>
<!ATTLIST price-volume-ratio    threshold                   CDATA #REQUIRED>

<!ELEMENT all EMPTY>

=== cbfaucher/qtrend/src/main/resources/exchange-configuration.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- TODO: XSD Please -->
<!--<!DOCTYPE exchange-configuration SYSTEM "http://quartz.com/dtd/exchange-configuration.dtd">-->

<exchange-configuration>

    <exchange   name="OBB"
                minimum-price="0.005"
                minimum-volume="100000" >
        <includes>
            <price-volume-ratio average-capital-invested="2000" threshold="0.05"/>
        </includes>
    </exchange>

    <exchange   name="NYSE"
                minimum-volume="1000000">
<!--        <includes>-->
<!--            -->
<!--        </includes>-->
        <excludes>
            <all/>
        </excludes>
    </exchange>

    <exchange   name="NASDAQ"
                minimum-volume="1000000">
<!--        <includes>-->
<!--            -->
<!--        </includes>-->
        <excludes>
            <all/>
        </excludes>
    </exchange>

    <exchange name="TSE" >
<!--
        <includes>
            <all/>
        </includes>
-->
        <excludes>
            <all/>
        </excludes>
    </exchange>

    <exchange name="VSE" >
<!--
        <includes>
            <all/>
        </includes>
-->
        <excludes>
            <all/>
        </excludes>
    </exchange>
</exchange-configuration>
